export interface City {
  city: string
  name: string
  utcOffset: string
  offsetMinutes: number
}

export const CITIES: City[] = [
  { city: 'London', name: 'GMT', utcOffset: 'UTC+0', offsetMinutes: 0 },
  { city: 'Reykjavik', name: 'GMT', utcOffset: 'UTC+0', offsetMinutes: 0 },
  { city: 'Lisbon', name: 'WET', utcOffset: 'UTC+0', offsetMinutes: 0 },
  { city: 'Paris', name: 'CET', utcOffset: 'UTC+1', offsetMinutes: 60 },
  { city: 'Berlin', name: 'CET', utcOffset: 'UTC+1', offsetMinutes: 60 },
  { city: 'Geneva', name: 'CET', utcOffset: 'UTC+1', offsetMinutes: 60 },
  { city: 'Madrid', name: 'CET', utcOffset: 'UTC+1', offsetMinutes: 60 },
  { city: 'Rome', name: 'CET', utcOffset: 'UTC+1', offsetMinutes: 60 },
  { city: 'Amsterdam', name: 'CET', utcOffset: 'UTC+1', offsetMinutes: 60 },
  { city: 'Vienna', name: 'CET', utcOffset: 'UTC+1', offsetMinutes: 60 },
  { city: 'Zurich', name: 'CET', utcOffset: 'UTC+1', offsetMinutes: 60 },
  { city: 'Lagos', name: 'WAT', utcOffset: 'UTC+1', offsetMinutes: 60 },
  { city: 'Johannesburg', name: 'SAST', utcOffset: 'UTC+2', offsetMinutes: 120 },
  { city: 'Cairo', name: 'EET', utcOffset: 'UTC+2', offsetMinutes: 120 },
  { city: 'Helsinki', name: 'EET', utcOffset: 'UTC+2', offsetMinutes: 120 },
  { city: 'Athens', name: 'EET', utcOffset: 'UTC+2', offsetMinutes: 120 },
  { city: 'Nairobi', name: 'EAT', utcOffset: 'UTC+3', offsetMinutes: 180 },
  { city: 'Istanbul', name: 'TRT', utcOffset: 'UTC+3', offsetMinutes: 180 },
  { city: 'Moscow', name: 'MSK', utcOffset: 'UTC+3', offsetMinutes: 180 },
  { city: 'Riyadh', name: 'AST', utcOffset: 'UTC+3', offsetMinutes: 180 },
  { city: 'Dubai', name: 'GST', utcOffset: 'UTC+4', offsetMinutes: 240 },
  { city: 'Abu Dhabi', name: 'GST', utcOffset: 'UTC+4', offsetMinutes: 240 },
  { city: 'Kabul', name: 'AFT', utcOffset: 'UTC+4:30', offsetMinutes: 270 },
  { city: 'Karachi', name: 'PKT', utcOffset: 'UTC+5', offsetMinutes: 300 },
  { city: 'Mumbai', name: 'IST', utcOffset: 'UTC+5:30', offsetMinutes: 330 },
  { city: 'Delhi', name: 'IST', utcOffset: 'UTC+5:30', offsetMinutes: 330 },
  { city: 'Colombo', name: 'SLST', utcOffset: 'UTC+5:30', offsetMinutes: 330 },
  { city: 'Dhaka', name: 'BST', utcOffset: 'UTC+6', offsetMinutes: 360 },
  { city: 'Rangoon', name: 'MMT', utcOffset: 'UTC+6:30', offsetMinutes: 390 },
  { city: 'Bangkok', name: 'ICT', utcOffset: 'UTC+7', offsetMinutes: 420 },
  { city: 'Jakarta', name: 'WIB', utcOffset: 'UTC+7', offsetMinutes: 420 },
  { city: 'Singapore', name: 'SGT', utcOffset: 'UTC+8', offsetMinutes: 480 },
  { city: 'Hong Kong', name: 'HKT', utcOffset: 'UTC+8', offsetMinutes: 480 },
  { city: 'Kuala Lumpur', name: 'MYT', utcOffset: 'UTC+8', offsetMinutes: 480 },
  { city: 'Manila', name: 'PST', utcOffset: 'UTC+8', offsetMinutes: 480 },
  { city: 'Taipei', name: 'CST', utcOffset: 'UTC+8', offsetMinutes: 480 },
  { city: 'Perth', name: 'AWST', utcOffset: 'UTC+8', offsetMinutes: 480 },
  { city: 'Beijing', name: 'CST', utcOffset: 'UTC+8', offsetMinutes: 480 },
  { city: 'Tokyo', name: 'JST', utcOffset: 'UTC+9', offsetMinutes: 540 },
  { city: 'Seoul', name: 'KST', utcOffset: 'UTC+9', offsetMinutes: 540 },
  { city: 'Osaka', name: 'JST', utcOffset: 'UTC+9', offsetMinutes: 540 },
  { city: 'Sydney', name: 'AEST', utcOffset: 'UTC+10', offsetMinutes: 600 },
  { city: 'Melbourne', name: 'AEST', utcOffset: 'UTC+10', offsetMinutes: 600 },
  { city: 'Brisbane', name: 'AEST', utcOffset: 'UTC+10', offsetMinutes: 600 },
  { city: 'Auckland', name: 'NZST', utcOffset: 'UTC+12', offsetMinutes: 720 },
  { city: 'Honolulu', name: 'HST', utcOffset: 'UTC-10', offsetMinutes: -600 },
  { city: 'Anchorage', name: 'AKST', utcOffset: 'UTC-9', offsetMinutes: -540 },
  { city: 'Los Angeles', name: 'PST', utcOffset: 'UTC-8', offsetMinutes: -480 },
  { city: 'Denver', name: 'MST', utcOffset: 'UTC-7', offsetMinutes: -420 },
  { city: 'Chicago', name: 'CST', utcOffset: 'UTC-6', offsetMinutes: -360 },
  { city: 'Mexico City', name: 'CST', utcOffset: 'UTC-6', offsetMinutes: -360 },
  { city: 'New York', name: 'EST', utcOffset: 'UTC-5', offsetMinutes: -300 },
  { city: 'Toronto', name: 'EST', utcOffset: 'UTC-5', offsetMinutes: -300 },
  { city: 'Lima', name: 'PET', utcOffset: 'UTC-5', offsetMinutes: -300 },
  { city: 'Bogotá', name: 'COT', utcOffset: 'UTC-5', offsetMinutes: -300 },
  { city: 'Caracas', name: 'VET', utcOffset: 'UTC-4', offsetMinutes: -240 },
  { city: 'Halifax', name: 'AST', utcOffset: 'UTC-4', offsetMinutes: -240 },
  { city: 'São Paulo', name: 'BRT', utcOffset: 'UTC-3', offsetMinutes: -180 },
  { city: 'Buenos Aires', name: 'ART', utcOffset: 'UTC-3', offsetMinutes: -180 },
  { city: 'Montevideo', name: 'UYT', utcOffset: 'UTC-3', offsetMinutes: -180 },
  { city: 'Azores', name: 'AZOT', utcOffset: 'UTC-1', offsetMinutes: -60 },
]
